spring.data.mongodb.uri=mongodb+srv://trichuthanh:z9KMoKKHieqtvTgN@salesdb-dev.f0h17vh.mongodb.net/?retryWrites=true&w=majority&appName=salesdb-dev&tls=true
spring.data.mongodb.database=salesdb-dev
app.jwt.secret=sandro-sales-dev-secret-2025-very-long-and-secure-key!
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trictps03805@gmail.com
spring.mail.password=ibpp sdch ajul xdnd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.frontend.verify-url=http://localhost:5173/verify
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.file-size-threshold=512KB
# AWS S3
aws.s3.access-key=${AWS_ACCESS_KEY}
aws.s3.secret-key=${AWS_SECRET_KEY}
aws.s3.region=${AWS_REGION:ap-southeast-1}
# G?i ? region t?t nh?t cho Vi?t Nam: ap-southeast-1 (Singapore) ho?c ap-southeast-2 (Sydney)
aws.s3.bucket=${AWS_S3_BUCKET}
spring.jackson.time-zone=Asia/Ho_Chi_Minh
webhook.secret=your-webhook-secret
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
app.fe.url=http://localhost:5173
app.reset-token.expiry-minutes=15
app.google.client-id=${GOOGLE_CLIENT_ID}
app.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.cache.type=simple
#spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379