package com.example.sales.constant;

import lombok.Getter;

@Getter
public enum ApiErrorCode {
    UNAUTHORIZED("ERR_401", "UNAUTHORIZED"),
    FORBIDDEN("ERR_403", "FORBIDDEN"),
    NOT_FOUND("ERR_404", "NOT_FOUND"),
    INTERNAL_ERROR("ERR_500", "INTERNAL_ERROR"),
    ACCESS_DENIED("ERR_403_ACCESS_DENIED", "ACCESS_DENIED"),
    VALIDATION_ERROR("ERR_400_VALIDATION", "VALIDATION_ERROR"),
    EMAIL_EXISTS("ERR_400_EMAIL_EXISTS", "EMAIL_EXISTS"),
    USER_NOT_FOUND("ERR_404_USER_NOT_FOUND", "USER_NOT_FOUND"),
    INVALID_TOKEN("ERR_400_INVALID_TOKEN", "INVALID_TOKEN"),
    ALREADY_VERIFIED("ERR_400_ALREADY_VERIFIED", "ALREADY_VERIFIED"),
    TOKEN_EXPIRED("ERR_400_TOKEN_EXPIRED", "TOKEN_EXPIRED"),
    EMAIL_NOT_VERIFIED("ERR_400_EMAIL_NOT_VERIFIED", "EMAIL_NOT_VERIFIED"),
    REFRESH_TOKEN_INVALID("ERR_400_REFRESH_TOKEN_INVALID", "REFRESH_TOKEN_INVALID"),
    REFRESH_TOKEN_EXPIRED("ERR_400_REFRESH_TOKEN_EXPIRED", "REFRESH_TOKEN_EXPIRED"),
    INCORRECT_PASSWORD("INCORRECT_PASSWORD", "INCORRECT_PASSWORD"),
    CUSTOMER_NOT_FOUND("CUSTOMER_NOT_FOUND", "CUSTOMER_NOT_FOUND"),
    CANNOT_DELETE_SELF("CANNOT_DELETE_SELF", "CANNOT_DELETE_SELF"),
    SHOP_ALREADY_EXISTS("SHOP_ALREADY_EXISTS", "SHOP_ALREADY_EXISTS"),
    SHOP_NOT_FOUND("SHOP_NOT_FOUND", "SHOP_NOT_FOUND"),
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND", "PRODUCT_NOT_FOUND"),
    TABLE_NOT_FOUND("TABLE_NOT_FOUND", "TABLE_NOT_FOUND"),
    ORDER_NOT_FOUND("ORDER_NOT_FOUND", "ORDER_NOT_FOUND"),
    ORDER_ALREADY_PAID("ORDER_ALREADY_PAID", "ORDER_ALREADY_PAID"),
    INVALID_STATUS_TRANSITION("INVALID_STATUS_TRANSITION", "INVALID_STATUS_TRANSITION"),
    PRODUCT_OUT_OF_STOCK("PRODUCT_OUT_OF_STOCK", "PRODUCT_OUT_OF_STOCK");


    private final String code;
    private final String message;

    ApiErrorCode(String code, String message) {
        this.code = code;
        this.message = message;
    }
}
