package com.example.sales.constant;

public enum ApiMessage {
    SUCCESS("SUCCESS", "SUCCESS"),
    REGISTER_SUCCESS("REGISTER_SUCCESS", "REGISTER_SUCCESS"),
    LOGIN_SUCCESS("LOGIN_SUCCESS", "LOGIN_SUCCESS"),
    PASSWORD_RESET_SENT("PASSWORD_RESET_SENT", "PASSWORD_RESET_SENT"),
    VERIFICATION_EMAIL_SENT("VERIFICATION_EMAIL_SENT", "VERIFICATION_EMAIL_SENT"),
    PRODUCT_CREATED("PRODUCT_CREATED", "PRODUCT_CREATED"),
    PRODUCT_UPDATED("PRODUCT_UPDATED", "PRODUCT_UPDATED"),
    PRODUCT_DELETED("PRODUCT_DELETED", "PRODUCT_DELETED"),
    PRODUCT_LIST("PRODUCT_LIST", "PRODUCT_LIST"),
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND", "PRODUCT_NOT_FOUND"),
    USER_NOT_FOUND("USER_NOT_FOUND", "USER_NOT_FOUND"),
    ACCESS_DENIED("ACCESS_DENIED", "ACCESS_DENIED"),
    ORDER_CREATED("ORDER_CREATED", "ORDER_CREATED"),
    ORDER_UPDATED("ORDER_UPDATED", "ORDER_UPDATED"),
    ORDER_DELETED("ORDER_DELETED", "ORDER_DELETED"),
    ORDER_LIST("ORDER_LIST", "ORDER_LIST"),
    ORDER_CANCELLED("ORDER_CANCELLED", "ORDER_CANCELLED"),
    ORDER_STATUS_UPDATED("ORDER_STATUS_UPDATED", "ORDER_STATUS_UPDATED"),
    VERIFY_SUCCESS("VERIFY_SUCCESS", "VERIFY_SUCCESS"),
    EMAIL_VERIFICATION_SENT("EMAIL_VERIFICATION_SENT", "EMAIL_VERIFICATION_SENT"),
    REFRESH_SUCCESS("REFRESH_SUCCESS", "REFRESH_SUCCESS"),
    LOGOUT_SUCCESS("LOGOUT_SUCCESS", "LOGOUT_SUCCESS"),
    USER_INFO("USER_INFO", "USER_INFO"),
    USER_UPDATED("USER_UPDATED", "USER_UPDATED"),
    PASSWORD_CHANGED("PASSWORD_CHANGED", "PASSWORD_CHANGED"),
    USER_LIST("USER_LIST", "USER_LIST"),
    USER_DETAIL("USER_DETAIL", "USER_DETAIL"),
    CUSTOMER_LIST("CUSTOMER_LIST", "CUSTOMER_LIST"),
    CUSTOMER_CREATED("CUSTOMER_CREATED", "CUSTOMER_CREATED"),
    CUSTOMER_UPDATED("CUSTOMER_UPDATED", "CUSTOMER_UPDATED"),
    CUSTOMER_DELETED("CUSTOMER_DELETED", "CUSTOMER_DELETED"),
    USER_DELETED("USER_DELETED", "USER_DELETED");

    private final String code;
    private final String message;

    ApiMessage(String code, String message) {
        this.code = code;
        this.message = message;
    }

    public String getCode() { return code; }

    public String getMessage() { return message; }
}
